version: '3'
services:
#  loggin-event-dispatcher:
#    container_name: loggin-event-dispatcher
#    image: 101digital/santander-logging-event-dispatcher:latest
#    hostname: logging
#    domainname: dev.io
#    ports:
#    - 10080:10080
#    environment:
#    - KAFKA=kafka.dev.io:9092
#    - RABBITMQ_HOST=rabbitmq.dev.io
#    restart: unless-stopped
#    networks:
#      service-network:
#        aliases:
#        - logging.dev.io
#  rabbitmq:
#     container_name: rabbitmq
#     image: rabbitmq:3-management
#     hostname: rabbitmq
#     domainname: dev.io
#     ports:
#     - 5672:5672
#     - 15672:15672
#     restart: unless-stopped
#     volumes:
#     - ./data/rabbitmq:/var/lib/rabbitmq
#     networks:
#       service-network:
#         aliases:
#         - rabbitmq.dev.io
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    hostname: zookeeper
    domainname: dev.io
    environment:
    - ZOO_SERVER_ID=1
    - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      service-network:
        aliases:
        - zookeeper.dev.io
  kafka:
    image: 'bitnami/kafka:latest'
    hostname: kafka
    domainname: dev.io
    ports:
    - 9092:9092
    environment:
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper.dev.io:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_BROKER_ID=1
    - KAFKA_NETWORK_OPTS=-Djava.net.preferIPv4Stack=True
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
    - KAFKA_CFG_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:29092,
    - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:29092
    - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:9092,EXTERNAL://localhost:29092
    - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
#    - KAFKA_MAX_MESSAGE_BYTES=20971520
#    - KAFKA_CFG_MESSAGE_MAX_BYTES=20971520
    - KAFKA_SOCKET_REQUEST_MAX_BYTES=20971520
#    - KAFKA_MAX_MESSAGE_BYTES=20971520
#    - KAFKA_SOCKET_REQUEST_MAX_BYTES=20971520
#    - CONNECT_MAX_REQUEST_SIZE=20971520
#    - KAFKA_MAX_REQUEST_SIZE=20971520
#    - KAFKA_PRODUCER_MAX_REQUEST_SIZE=20971520
#    - CONNECT_PRODUCER_MAX_REQUEST_SIZE=20971520
    networks:
      service-network:
        aliases:
        - kafka.dev.io
#    volumes:
#    - ./data/kafka/server.properties:/opt/bitnami/kafka/conf/server.properties
#  passbolt:
#    image: passbolt/passbolt:latest-ce
#    tty: true
#    env_file:
#      - /SSD/devel/passbolt/passbolt.env
#    volumes:
#      - gpg_volume:/SSD/devel/passbolt/gpg
#      - images_volume:/SSD/devel/passbolt/webroot/img/public
#    command: ["/usr/bin/wait-for.sh", "-t", "0", "mysql.dev.robin:3306", "--", "/docker-entrypoint.sh"]
#    hostname: passbolt.dev.io
#    networks:
#      service-network:
volumes:
  database_volume:
  gpg_volume:
  images_volume:

networks:
 service-network:
    external:
      name: service-network
