apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kafka
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - env:
            - name: 'KAFKA_CFG_ZOOKEEPER_CONNECT'
              value: 'host.minikube.internal:2181'
            - name: 'ALLOW_PLAINTEXT_LISTENER'
              value: 'yes'
            - name: 'KAFKA_BROKER_ID'
              value: '1'
            - name: 'KAFKA_CFG_LISTENERS'
              value: 'CLIENT://:9092'
            - name: 'KAFKA_NETWORK_OPTS'
              value: '-Djava.net.preferIPv4Stack=True'
            - name: 'KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP'
              value: 'CLIENT:PLAINTEXT'
            - name: 'KAFKA_ADVERTISED_LISTENERS'
              value: 'CLIENT://kafka:9092'
            - name: 'KAFKA_CFG_ADVERTISED_LISTENERS'
              value: 'CLIENT://kafka:9092'
            - name: 'KAFKA_INTER_BROKER_LISTENER_NAME'
              value: 'CLIENT'
            - name: 'KAFKA_SOCKET_REQUEST_MAX_BYTES'
              value: '20971520'
          image: 'bitnami/kafka:latest'
          imagePullPolicy: IfNotPresent
          name: kafka
          ports:
            - containerPort: 9092
              name: kafka
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---

apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: default
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 9092
      protocol: TCP
      targetPort: 9092
      nodePort: 32092
  selector:
    app: kafka
  sessionAffinity: None
  type: NodePort
