#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  labels:
#    type: local
#  name: bitnamidockerzookeeper-zookeeper-data
#spec:
#  accessModes:
#    - ReadWriteOnce
#  capacity:
#    storage: 20Gi
#  hostPath:
#    path: /hhd/data/zookeeper
#    type: ""
#  persistentVolumeReclaimPolicy: Retain
#  storageClassName: manual
#  volumeMode: Filesystem
#
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: bitnamidockerzookeeper-zookeeper-data
#  namespace: default
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 20Gi
#  storageClassName: manual
#  volumeMode: Filesystem
#  volumeName: bitnamidockerzookeeper-zookeeper-data
#
#---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: zookeeper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - env:
        - name: 'ZOO_SERVER_ID'
          value: '1'
        - name: 'ALLOW_ANONYMOUS_LOGIN'
          value: 'yes'
        - name: 'ZOO_4LW_COMMANDS_WHITELIST'
          value: '*'
        - name: 'ZOO_LOG_LEVEL'
          value: 'ALL'
#        - name: 'ZOO_SERVERS'
#          value: '0.0.0.0:2888:3888'
        image: 'bitnami/zookeeper:3.7'
        imagePullPolicy: IfNotPresent
        name: zookeeper
        ports:
        - containerPort: 2888
          name: tcp-2888
          protocol: TCP
        - containerPort: 3888
          name: tcp-3888
          protocol: TCP
        - containerPort: 2181
          name: zookeeper
          protocol: TCP
        resources: {}
#        volumeMounts:
#          - mountPath: /bitnami/zookeeper
#            name: bitnamidockerzookeeper-zookeeper-data
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
#      volumes:
#      - name: bitnamidockerzookeeper-zookeeper-data
#        persistentVolumeClaim:
#          claimName: bitnamidockerzookeeper-zookeeper-data
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: default
spec:
  ports:
    - port: 2181
      protocol: TCP
      #targetPort: 2181
      #nodePort: 32181
  selector:
    app: zookeeper
  sessionAffinity: None
  #type: NodePort
